trigger:
- main

variables:
- group: TerraformSecrets
- name: environment
  value: 'dev'
- name: resgrp
  value: 'terraform-rg'
- name: storageAcc
  value: 'terraformstorageuw'
- name: storageContrainer
  value: 'terraform-container'
- name: backendKey
  value: 'vnetDemo1.terraform.tfstate'
- name: location
  value: 'eastus'
- name: system.debug
  value: true

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: TerraformBackendSetup
    displayName: Check and Create Storage Account
    jobs:
      - job: CheckCreateStorageAct
        steps:
        - task: AzureCLI@2
          inputs:
            azureSubscription: 'AzureRM2'
            scriptType: 'bash'
            scriptLocation: 'inlineScript'
            inlineScript: |
              az group create --location $(location) --name $(resgrp)
              if ! az storage account check-name --name $(storageAcc) --query 'nameAvailable' | grep -q true; then
                echo "Storage account exists."
                if az storage container exists --name $(storageContrainer) --account-name $(storageAcc) --query 'exists' | grep -q true; then
                  echo "Container exists."
                else
                  echo "Container does not exist. Creating container."
                  az storage container create --name $(storageContrainer) --account-name $(storageAcc)
                fi
              else
                echo "Storage account does not exist. Creating storage account and container."
                az storage account create --name $(storageAcc) --resource-group $(resgrp) --location eastus --sku Standard_LRS
                az storage container create --name $(storageContrainer) --account-name $(storageAcc)
              fi
  - stage: TerraformValidate
    displayName: Deploy Terraform Infrastructure
    dependsOn: TerraformBackendSetup
    jobs:
      - job: validate
        steps:
        - task: TerraformInstaller@1
          displayName: tfInstall
          inputs:
            terraformVersion: '1.5.7'

        - task: TerraformTaskV4@4
          displayName: "init"
          inputs:
            provider: 'azurerm'
            command: 'init'
            backendServiceArm: 'AzureRM2'
            backendAzureRmResourceGroupName: '$(resgrp)'
            backendAzureRmStorageAccountName: '$(storageAcc)'
            backendAzureRmContainerName: '$(storageContrainer)'
            backendAzureRmKey: '$(backendKey)'
            workingDirectory: '$(System.DefaultWorkingDirectory)/DemoVnet01'
        - task: TerraformTaskV4@4
          displayName: "validate"
          inputs:
            provider: 'azurerm'
            command: 'validate'
            workingDirectory: '$(System.DefaultWorkingDirectory)/DemoVnet01'
  - stage: TerraformDeploy
    condition: succeeded('TerraformValidate')
    dependsOn: TerraformValidate
    jobs:
      - job: apply
        steps:
          - script: |
              echo "Printing environment variables for debugging:"
              printenv
            displayName: "Print Environment Variables"
          - task: TerraformInstaller@1
            displayName: tfInstall
            inputs:
              terraformVersion: '1.5.7'
          - task: TerraformTaskV4@4
            displayName: "init"
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'AzureRM2'
              backendAzureRmResourceGroupName: '$(resgrp)'
              backendAzureRmStorageAccountName: '$(storageAcc)'
              backendAzureRmContainerName: '$(storageContrainer)'
              backendAzureRmKey: '$(backendKey)'
              #workingDirectory: '$(System.DefaultWorkingDirectory)/DemoVnet01'
          - task: TerraformTaskV4@4
            displayName: plan
            inputs:
              provider: 'azurerm'
              command: 'plan'
              environmentServiceNameAzureRM: 'AzureRM2'
              #workingDirectory: '$(System.DefaultWorkingDirectory)/DemoVnet01'
          - task: TerraformTaskV4@4
            displayName: apply
            inputs:
              provider: 'azurerm'
              command: 'apply'
              environmentServiceNameAzureRM: 'AzureRM2'
              workingDirectory: '$(System.DefaultWorkingDirectory)/DemoVnet01'
              commandOptions: '-auto-approve'