trigger:
- main

variables:
  environment: 'dev'
  resgrp: 'teraform-rg'
  storageAcc: 'tdemosa1'
  storageContrainer: 'terraform-container'
  backendKey: 'dev.terraform.tfstate'

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: TerraformValidate
    displayName: Deploy Terraform Infrastructure
    jobs:
      - job: validate
        continueOnError: false
        steps:
        - task: TerraformInstaller@1
          displayName: tfInstall
          inputs:
            terraformVersion: 'latest'
        - task: TerraformTaskV4@4
          displayName: "init"
          inputs:
            provider: 'azurerm'
            command: 'init'
            backendServiceArm: 'AzureRM'
            backendAzureRmResourceGroupName: '$(resgrp)'
            backendAzureRmStorageAccountName: '$(storageAcc)'
            backendAzureRmContainerName: '$(storageContrainer)'
            backendAzureRmKey: '$(backendKey)'
            workingDirectory: '$(System.DefaultWorkingDirectory)/path/to/Demovnet01'
        - task: TerraformTaskV4@4
          displayName: "validate"
          inputs:
            provider: 'azurerm'
            command: 'validate'
            workingDirectory: '$(System.DefaultWorkingDirectory)/path/to/Demovnet01'
  - stage: TerraformDeploy
    condition: succeeded('TerraformValidate')
    dependsOn: TerraformValidate
    jobs:
      - job: apply
        steps:
          - task: TerraformInstaller@1
            displayName: tfInstall
            inputs:
              terraformVersion: 'latest'
          - task: TerraformTaskV4@4
            displayName: "init"
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'AzureRM'
              backendAzureRmResourceGroupName: '$(resgrp)'
              backendAzureRmStorageAccountName: '$(storageAcc)'
              backendAzureRmContainerName: '$(storageContrainer)'
              backendAzureRmKey: '$(backendKey)'
              workingDirectory: '$(System.DefaultWorkingDirectory)/path/to/Demovnet01'
          - task: TerraformTaskV4@4
            displayName: plan
            inputs:
              provider: 'azurerm'
              command: 'plan'
              environmentServiceNameAzureRM: 'AzureRM'
              workingDirectory: '$(System.DefaultWorkingDirectory)/path/to/Demovnet01'
          - task: TerraformTaskV4@4
            displayName: apply
            inputs:
              provider: 'azurerm'
              command: 'apply'
              environmentServiceNameAzureRM: 'AzureRM'
              workingDirectory: '$(System.DefaultWorkingDirectory)/path/to/Demovnet01'